---
name: BottleXP
version: 1.0.0
main: iRainDrop\BottleXP\Main
api: 5.0.0
src-namespace-prefix: iRainDrop\BottleXP

permissions:
  bottlexp.cmd:
    description: Allows users to use this command
    default: true
...
